version: "3.8"

services:
  proxy:
    build: ./nginx-conf
    ports:
      - 8080:80
  auth:
    build: .
    # ports:
    #   - 8081:80
    environment:
      APP: auth
    command:
      - auth:app
  private:
    build: .
    # ports:
    #   - 8082:80
    environment:
      APP: private
    command:
      - private:app
